//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatRoom.Utilities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatRoom.Utilities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string AllNickname {
            get {
                return ResourceManager.GetString("AllNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [FAILED] {0} (to {1}) Type: {2} | {3}.
        /// </summary>
        internal static string LogMessageFailed {
            get {
                return ResourceManager.GetString("LogMessageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | {1} .
        /// </summary>
        internal static string LogMessageToAllUnfmt {
            get {
                return ResourceManager.GetString("LogMessageToAllUnfmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (to {1}) | {2}.
        /// </summary>
        internal static string LogMessageToSpecificUnfmt {
            get {
                return ResourceManager.GetString("LogMessageToSpecificUnfmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (To {0}) {1}.
        /// </summary>
        internal static string PrivateMessageBodyUnfmt {
            get {
                return ResourceManager.GetString("PrivateMessageBodyUnfmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string PublicMessageBodyUnfmt {
            get {
                return ResourceManager.GetString("PublicMessageBodyUnfmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string ServerNickname {
            get {
                return ResourceManager.GetString("ServerNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is in the chat room..
        /// </summary>
        internal static string UserIsPresentUnfmt {
            get {
                return ResourceManager.GetString("UserIsPresentUnfmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has joined the chat room..
        /// </summary>
        internal static string UserJoinedUnfmt {
            get {
                return ResourceManager.GetString("UserJoinedUnfmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has left the chat room..
        /// </summary>
        internal static string UserLeftUnfmt {
            get {
                return ResourceManager.GetString("UserLeftUnfmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [ID:{1}].
        /// </summary>
        internal static string UserUnfmt {
            get {
                return ResourceManager.GetString("UserUnfmt", resourceCulture);
            }
        }
    }
}
