//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatRoom.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatRoom.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not bind to {0}:{1}. : {2}.
        /// </summary>
        internal static string BindFailedUnfmt {
            get {
                return ResourceManager.GetString("BindFailedUnfmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully bound to {0}:{1}..
        /// </summary>
        internal static string BindSuccessfulUnfmt {
            get {
                return ResourceManager.GetString("BindSuccessfulUnfmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client at {0} disconnected..
        /// </summary>
        internal static string ClientInitializationFailedUnfmt {
            get {
                return ResourceManager.GetString("ClientInitializationFailedUnfmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message recieved from {0}. : {1}.
        /// </summary>
        internal static string InvalidMessageUnfmt {
            get {
                return ResourceManager.GetString("InvalidMessageUnfmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening for client connections....
        /// </summary>
        internal static string Listening {
            get {
                return ResourceManager.GetString("Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection from {0}..
        /// </summary>
        internal static string NewConnectionUnfmt {
            get {
                return ResourceManager.GetString("NewConnectionUnfmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the Chat Room Server....
        /// </summary>
        internal static string StartingServer {
            get {
                return ResourceManager.GetString("StartingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured. : {0}.
        /// </summary>
        internal static string UnknownErrorUnfmt {
            get {
                return ResourceManager.GetString("UnknownErrorUnfmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has disconnected..
        /// </summary>
        internal static string UserDisconnectedUnfmt {
            get {
                return ResourceManager.GetString("UserDisconnectedUnfmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be found in the chat room..
        /// </summary>
        internal static string UserNotFoundUnfmt {
            get {
                return ResourceManager.GetString("UserNotFoundUnfmt", resourceCulture);
            }
        }
    }
}
